### ISSUE TITLE
An error occurred when reading from api.twitter.com： reply too long length (limit 524288 )

### ISSUE THREAD

**Issue by wxg4net** [fr0nk/microblog-purple2#2]
see above

util: Defaulting max download from https://api.twitter.com/1.1/account/verify_credentials.json to 524288

**Comment by fr0nk** [comment]
Thats most likely the initial fetching of the timeline. By default it gets the last 15 tweets. You can change this in the account settings on the Advanced Tab "Number of initial tweets". Change this to 10 or something on account creation and it should work.

**Comment by perhome** [comment]
Change this to 1 . error again. here is screenshot  http://t.cn/RhWGkG0
